domElementsConfig = {}

//mediaDir = "./"
mediaDir = "./media/"

domElementsConfig_pp = {

  "domElement-video-0": {
    "left": "0px",
    "top": "0px",
    "height": "1080px",
    "width": "1920px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "grey",
    "background-color": "none",
    "border": "0px solid green",
    "innerText": "Video Object",
    "className": "domElement-video",
    "zIndex": "0",
    "src": mediaDir + "background_pp.webm",
    "loop": "false"
  },
  
  "domElement-image-sombra-1": {
    "left": "1225px",
    "top": "45px",
    "height": "1000px",
    "width": "595px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "sombra.png",
    "className": "domElement-image",
    "zIndex": "1"
  },


  "domElement-image-sombra-2": {
    "left": "550px",
    "top": "675px",
    "height": "375px",
    "width": "595px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "sombra.png",
    "className": "domElement-image",
    "zIndex": "1"
  },


  "domElement-image-sombra-3": {
    "left": "1245px",
    "top": "375px",
    "height": "330px",
    "width": "555px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "sombra.png",
    "className": "domElement-image",
    "zIndex": "1"
  },

  "domElement-image-sombra-4": {
    "left": "1245px",
    "top": "720px",
    "height": "300px",
    "width": "555px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "sombra.png",
    "className": "domElement-image",
    "zIndex": "1"
  },


  
  "domElement-text-header-location": {
    "left": "1275px",
    "top": "115px",
    "height": "95px",
    "width": "500px",
    "font-size": "90px",
    "font-family": "Arial",
    "text-align": "center",
    "font-weight": "bold",
    "color": "white",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "MEDELLÍN",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-vtype-1": {
    "left": "625px",
    "top": "700px",
    "height": "",
    "width": "",
    "font-size": "55px",
    "font-family": "Arial",
    "text-align": "center",
    "color": "white",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "Carros particulares",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-vtype-2": {
    "left": "600px",
    "top": "795px",
    "height": "",
    "width": "",
    "font-size": "35px",
    "font-family": "Arial",
    "text-align": "center",
    "color": "grey",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "Con el último numero de la placa",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-vtype-3": {
    "left": "615px",
    "top": "885px",
    "height": "",
    "width": "",
    "font-size": "55px",
    "font-family": "Arial",
    "text-align": "center",
    "color": "white",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "Motos 2 y 4 tiempos",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-vtype-4": {
    "left": "590px",
    "top": "975px",
    "height": "",
    "width": "",
    "font-size": "35px",
    "font-family": "Arial",
    "text-align": "center",
    "color": "grey",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "Con el primer numero de la placa",
    "className": "domElement-text",
    "zIndex": "3"
  },  
  "domElement-text-horario": {
    "left": "1385px",
    "top": "255px",
    "height": "",
    "width": "",
    "font-size": "35px",
    "font-family": "Arial",
    "text-align": "Right",
    "color": "white",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "5:00 am - 8:00 pm   ",
    "className": "domElement-text",
    "zIndex": "3"
  },

  "domElement-text-5-1": {
    "left": "1465px",
    "top": "375px",
    "height": "",
    "width": "",
    "font-size": "45px",
    "font-family": "Verdana",
    "font-weight": "bold",
    "text-align": "right",
    "color": "grey",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "HOY",
    "className": "domElement-text",
    "zIndex": "3"
  },

  "domElement-text-5-2": {
    "left": "1435px",
    "top": "720px",
    "height": "",
    "width": "",
    "font-size": "50px",
    "font-family": "Arial",
    "text-align": "right",
    "color": "grey",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "MAÑANA",
    "className": "domElement-text",
    "zIndex": "3"
  },

  "domElement-text-5-sep-1": {
    "left": "1490px",
    "top": "500px",
    "height": "",
    "width": "",
    "font-size": "99px",
    "font-family": "Arial",
    "text-align": "right",
    "color": "white",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "-",
    "className": "domElement-text",
    "zIndex": "3"
  },

  "domElement-text-5-sep-2": {
    "left": "1500px",
    "top": "835px",
    "height": "",
    "width": "",
    "font-size": "99px",
    "font-family": "Arial",
    "text-align": "right",
    "color": "white",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "-",
    "className": "domElement-text",
    "zIndex": "3"
  },

  
  "domElement-text-autos-1-1": {
    "left": "1325px",
    "top": "425px",
    "height": "320px",
    "width": "200px",
    "font-size": "180px",
    "font-family": "Verdana",
    "text-align": "center",
    "color": "white",
    //"background-color": "#9FE2BF",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "-",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-autos-1-2": {
    "left": "1525px",
    "top": "425px",
    "height": "320px",
    "width": "200px",
    "font-size": "180px",
    "font-family": "Verdana",
    "text-align": "center",
    "color": "white",
    //"background-color": "#9FE2BF",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "-",
    "className": "domElement-text",
    "zIndex": "3"
  },
  
  "domElement-text-motos-1-1": {
    "left": "1385px",
    "top": "850px",
    "height": "150px",
    "width": "150px",
    "font-size": "90px",
    "font-family": "Verdana",
    "text-align": "center",
    "color": "white",
    //"background-color": "#9FE2BF",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "-",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-motos-1-2": {
    "left": "1500px",
    "top": "850px",
    "height": "150px",
    "width": "150px",
    "font-size": "90px",
    "font-family": "Verdana",
    "text-align": "center",
    "color": "white",
    //"background-color": "#9FE2BF",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "-",
    "className": "domElement-text",
    "zIndex": "3"
  },
  
  "domElement-text-header-1": {
    "left": "1175px",
    "top": "55px",
    "height": "95px",
    "width": "700px",
    "font-size": "45px",
    "font-family": "Arial",
    "text-align": "center",
    "color": "white",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "PICO Y PLACA",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-date-1": {
    "left": "1275px",
    "top": "450px",
    "height": "75px",
    "width": "500px",
    "font-size": "35px",
    "font-family": "Arial",
    "font-weight": "bold",
    "text-align": "center",
    "color": "white",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "Fecha",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-date-2": {
    "left": "1275px",
    "top": "800px",
    "height": "75px",
    "width": "500px",
    "font-size": "35px",
    "font-family": "Arial",
    "font-weight": "bold",
    "text-align": "center",
    "color": "white",
    "background-color": "none",
    "border": "0px solid #ccc",
    "innerText": "Fecha",
    "className": "domElement-text",
    "zIndex": "3"
  }

}

domElementsConfig_indeco = {
  "domElement-image-0": {
    "top": "0px",
    "left": "0px",
    "height": "1080px",
    "width": "1920px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Fondo.jpg",
    "className": "domElement-image",
    "zIndex": "1"
  },
  "domElement-image-1": {
    "left": "140px",
    "top": "100px",
    "height": "705px",
    "width": "1640px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "2"
  },
  "domElement-image-2": {
    "left": "460px",
    "top": "490px",
    "height": "277px",
    "width": "991px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "none",
    "src": mediaDir + "Lineas.png",
    "className": "domElement-image",
    "zIndex": "3"
  },
  "domElement-image-3": {
    "left": "160px",
    "top": "680px",
    "height": "75px",
    "width": "281px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-4": {
    "left": "488px",
    "top": "680px",
    "height": "75px",
    "width": "281px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-5": {
    "left": "816px",
    "top": "680px",
    "height": "75px",
    "width": "281px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-6": {
    "left": "1143px",
    "top": "680px",
    "height": "75px",
    "width": "281px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-7": {
    "left": "1476px",
    "top": "680px",
    "height": "75px",
    "width": "281px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-8": {
    "left": "271px",
    "top": "500px",
    "height": "39px",
    "width": "45px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-9": {
    "left": "612px",
    "top": "500px",
    "height": "39px",
    "width": "45px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-10": {
    "left": "946px",
    "top": "500px",
    "height": "39px",
    "width": "45px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-11": {
    "left": "1277px",
    "top": "500px",
    "height": "39px",
    "width": "45px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-12": {
    "left": "1596px",
    "top": "501px",
    "height": "39px",
    "width": "45px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-text-13": {
    "left": "185px",
    "top": "570px",
    "height": "95px",
    "width": "200px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "Café",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-14": {
    "left": "534px",
    "top": "570px",
    "height": "95px",
    "width": "200px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "UVR",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-15": {
    "left": "848px",
    "top": "570px",
    "height": "95px",
    "width": "200px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "Euro",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-16": {
    "left": "1202px",
    "top": "570px",
    "height": "95px",
    "width": "200px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "DTF",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-17": {
    "left": "1467px",
    "top": "570px",
    "height": "95px",
    "width": "300px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "Barril petróleo",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-18": {
    "left": "200px",
    "top": "100px",
    "height": "95px",
    "width": "1500px",
    "font-size": "120px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "Dólar (TRM)",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-19": {
    "left": "720px",
    "top": "300px",
    "height": "95px",
    "width": "500px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-image-backDolar": {
    "left": "805px",
    "top": "300px",
    "height": "100px",
    "width": "330px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-image-dirDolar": {
    "left": "700px",
    "top": "300px",
    "height": "100px",
    "width": "100px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "0px solid white",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "4"
  },
  "domElement-text-20": {
    "left": "150px",
    "top": "680px",
    "height": "95px",
    "width": "300px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-21": {
    "left": "475px",
    "top": "680px",
    "height": "95px",
    "width": "300px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-22": {
    "left": "806px",
    "top": "680px",
    "height": "95px",
    "width": "300px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-23": {
    "left": "1125px",
    "top": "680px",
    "height": "95px",
    "width": "300px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "-- %",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-24": {
    "left": "1510px",
    "top": "680px",
    "height": "95px",
    "width": "200px",
    "font-size": "40px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-25": {
    "left": "0px",
    "top": "921px",
    "height": "95px",
    "width": "800px",
    "font-size": "50px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "INDICADORES ECONÓMICOS",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-26": {
    "left": "1358px",
    "top": "800px",
    "height": "95px",
    "width": "500px",
    "font-size": "130px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "Medellín",
    "className": "domElement-text",
    "zIndex": "5"
  },
  "domElement-text-27": {
    "left": "1305px",
    "top": "968px",
    "height": "95px",
    "width": "600px",
    "font-size": "35px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "-----",
    "className": "domElement-text",
    "zIndex": "5"
  }
}

domElementsConfig_clima = {
  "domElement-image-0": {
    "left": "1300px",
    "top": "40px",
    "height": "10%",
    "width": "",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "none",
    "src": mediaDir + "Logo_Canal.png",
    "className": "domElement-image",
    "zIndex": "2"
  },
  "domElement-image-1": {
    "left": "0px",
    "top": "0px",
    "height": "1080px",
    "width": "1920px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "none",
    "src": mediaDir + "Sombra.png",
    "className": "domElement-image",
    "zIndex": "1"
  },
  "domElement-text-2": {
    "left": "50px",
    "top": "780px",
    "height": "95px",
    "width": "1500px",
    "font-size": "130px",
    "font-family": "Verdana",
    "text-align": "left",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-3": {
    "left": "59px",
    "top": "974px",
    "height": "95px",
    "width": "900px",
    "font-size": "35px",
    "font-family": "verdana",
    "text-align": "left",
    "color": "white",
    "background-color": "none",
    "border": "",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-video-4": {
    "left": "0px",
    "top": "0px",
    "height": "1080px",
    "width": "1920px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "grey",
    "background-color": "none",
    "border": "0px solid green",
    "innerText": "Video Object",
    "className": "domElement-video",
    "zIndex": "0",
    "src": "",
    "loop": "false"
  },
  "domElement-image-5": {
    "left": "1376px",
    "top": "150px",
    "height": "800px",
    "width": "500px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "none",
    "src": mediaDir + "Caja.png",
    "className": "domElement-image",
    "zIndex": "2"
  },
  "domElement-image-6": {
    "left": "900px",
    "top": "150px",
    "height": "800px",
    "width": "500px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": "none",
    "border": "none",
    "src": mediaDir + "Caja.png",
    "className": "domElement-image",
    "zIndex": "2"
  },
  "domElement-text-7": {
    "left": "1049px",
    "top": "210px",
    "height": "95px",
    "width": "200px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "Actual",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-8": {
    "left": "1490px",
    "top": "210px",
    "height": "95px",
    "width": "280px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "Pronóstico",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-9": {
    "left": "957px",
    "top": "480px",
    "height": "95px",
    "width": "400px",
    "font-size": "170px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-10": {
    "left": "1376px",
    "top": "480px",
    "height": "95px",
    "width": "500px",
    "font-size": "170px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-image-11": {
    "left": "1022px",
    "top": "284px",
    "height": "250px",
    "width": "250px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "none",
    "background-color": "none",
    "border": "none",
    "src": mediaDir + "Subir.png",
    "className": "domElement-image",
    "zIndex": "2"
  },
  "domElement-image-12": {
    "left": "1501px",
    "top": "293px",
    "height": "250px",
    "width": "250px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "none",
    "background-color": "none",
    "border": "none",
    "src": mediaDir + "1_386.png",
    "className": "domElement-image",
    "zIndex": "2"
  },
  "domElement-text-13": {
    "left": "925px",
    "top": "720px",
    "height": "95px",
    "width": "450px",
    "font-size": "35px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "3"
  },
  "domElement-text-14": {
    "left": "1425px",
    "top": "720px",
    "height": "95px",
    "width": "400px",
    "font-size": "35px",
    "font-family": "Arial",
    "color": "white",
    "background-color": "none",
    "border": "none",
    "innerText": "--",
    "className": "domElement-text",
    "zIndex": "3"
  }
}

// Enabled props for DOM elements and it's default values
domClassesProps = {
  "domElement-text": {
    "left": "50%",
    "top": "50%",
    "height": "95px",
    "width": "500px",
    "font-size": "55px",
    "font-family": "Arial",
    "text-align": "left",
    "color": "black",
    "background-color": 'white',
    "border": "0px solid #ccc",
    "innerText": "New obj text",
    "className": 'domElement-text',
    "zIndex": "3"
  },
  "domElement-image": {
    "left": "50%",
    "top": "50%",
    "height": "200px",
    "width": "200px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "black",
    "background-color": 'none',
    "border": "0px solid white",
    "src": mediaDir + "Subir.png",
    "className": 'domElement-image',
    "zIndex": "1"
  },
  "domElement-video": {
    "left": "50%",
    "top": "50%",
    "height": "500px",
    "width": "500px",
    "font-size": "55px",
    "font-family": "Arial",
    "color": "grey",
    "background-color": 'none',
    "border": "3px solid green",
    "innerText": "Video Object",
    "className": 'domElement-video',
    "zIndex": "3",
    "src": "",
    "loop": "false"
  },
}

//domElementsConfig = domElementsConfig_clima
domElementsConfig = domElementsConfig_pp
